security:
    password_hashers:
        App\Document\User:
            algorithm: auto

    providers:
        app_user_provider:
            mongodb:
                class: App\Document\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /
            remember_me:
                secret: "%kernel.secret%"

    access_control:
        - { path: ^/login }
        - { path: ^/ }
